### ISSUE TITLE
API KEY exposed

### ISSUE THREAD

**Issue by awaisabir** [ShaneMatthias/Youtube_Web_App#1]
https://github.com/ShaneMatthias/Youtube_Web_App/blob/master/src/index.js#L7
You do not need to expose your key to the whole world. It is better to place it in a config file and then import the variables you need for the file.

Create a `config` folder in `src` and place a `config.js` file in that folder. Your config file can be something like this:
```
export default {
  API_KEY: "place-key-here"
};
```
### Do not push the `config.js` file. Instead create another file in your config folder called `config.example.js` which will have the layout of the config file (similar to above)

and then in your `index.js` file add this statement:
` import { API_KEY } from '../path/to/config'`
and the use the `API_KEY` variable for the key.

Let me know if you have any questions 👏

**Comment by ShaneMatthias** [comment]
Thanks for letting me know.

API_KEY is undefined. Try this instead:

`import config from '../path/to/config'`

then use:

`config.API_KEY`

**Comment by awaisabir** [comment]
You might also want to remove the existence of the `config.js` file from your git commit's cache, so someone can't go to your commit history and see the commits with the key :)

`git rm --cached path/to/config.js`

**Comment by ShaneMatthias** [comment]
Bro you comment shit and destroy my app

**Comment by ShaneMatthias** [comment]
Gotcha!

Thanks a bunch!
